CREATE DATABASE QLSACH
ON 
(
	NAME = QLSACH_DATA,
	FILENAME = 'D:\QLSACH.MDF',
	SIZE = 8,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 2
)
LOG ON
(
	NAME = QLSACH_LOG,
	FILENAME = 'D:\QLSACH.LDF',
	SIZE = 8,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 2
)

USE QLSACH

CREATE TABLE CATEGORIES
(
	ID		INT IDENTITY,
	NAME	NVARCHAR(255) UNIQUE NOT NULL,
	CONSTRAINT PK_CATEGORIES PRIMARY KEY (ID)
)
GO

CREATE TABLE BOOKS
(
	ID		INT IDENTITY,
	NAME	NVARCHAR(255) UNIQUE NOT NULL,
	PRICE	FLOAT NOT NULL,
	ID_CATEGORY INT NOT NULL,
	CONSTRAINT PK_BOOKS PRIMARY KEY (ID),
	CONSTRAINT FK_BOOKS_CATEGORIES FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORIES(ID)
)
GO

INSERT INTO CATEGORIES VALUES
(N'Giáo dục'),
(N'Tâm lý'),
(N'Truyện tranh'),
(N'Khoa học')

INSERT INTO BOOKS VALUES
(N'Xác suất thống kê', 65000, 1),
(N'Toán A1', 60000, 1),
(N'Toán A2', 60000, 1),
(N'Lý thuyết đồ thị', 45000, 1),
(N'Đắc nhân tâm', 70000, 2),
(N'Tâm lý học',90000, 2),
(N'Dragon ball',45000, 3),
(N'One piece', 50000, 3),
(N'Nguồn gốc các loài', 66000, 4),
(N'Khoa học chiết xuất',88000, 4)

